import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";
import { readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const site = "https://www.ashtangayogazentralberlin.de";

// EN-only slugs get noindex meta-refresh redirect pages under /de/
// (generated by src/pages/de/[...slug].astro). Derive them from the content
// files (same layout as the glob loader in src/content.config.ts) so new
// EN-only pages are excluded from the sitemap automatically.
const mdxNames = (dir) =>
  readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isFile() && d.name.endsWith(".mdx"))
    .map((f) => f.name.replace(/\.mdx$/, ""))
    .filter((name) => name !== "index");
const pagesDir = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "src/content/pages",
);
const enSlugs = mdxNames(pagesDir);
const deSlugs = new Set(mdxNames(path.join(pagesDir, "de")));
const noindexRedirectUrls = enSlugs
  .filter((slug) => !deSlugs.has(slug))
  .map((slug) => new URL(`/de/${slug}/`, site).href);

export default defineConfig({
  integrations: [
    mdx(),
    sitemap({
      i18n: {
        defaultLocale: "en",
        locales: {
          en: "en-US",
          de: "de-DE",
        },
      },
      // @astrojs/sitemap v3: `filter` replaces the old `exclude` option.
      // Return false to drop a URL from the sitemap.
      filter: (url) => !noindexRedirectUrls.includes(url),
    }),
  ],
  site,
  base: "",

  i18n: {
    defaultLocale: "en",
    locales: ["de", "en"],
    routing: {
      prefixDefaultLocale: false,
      fallbackType: "redirect",
    },
    fallback: {
      de: "en",
    },
  },
});
